---
name: "LastFM"
guid: "5e7fe7f0-b048-429e-a431-b1a7e69c930d"
version: "10.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "A plugin that scrobbles your Jellyfin music to LastFM."
description: >
  Scrobble LastFM plays with Jellyfin.
category: "Music"
owner: "jesseward"
artifacts:
  - "Jellyfin.Plugin.Lastfm.dll"
changelog: >
  Support Jellyfin 10.11
